name: Run Compliance and Multitenancy tests
on: [ pull_request, push]
  branches:
  - environment*
  paths-ignore: 
    - '**/README.md'
    - 'README.md'
jobs:
  compliance-multitenancy-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: mikefarah/yq@v3.4.1
      - name: Run Script
        run: ./.github/script/compliance-mt.sh
        env: 
          GITHUB_BASE_REF: ${{ secrets.GITHUB_BASE_REF }}
