name: Run Compliance and Multitenancy tests
on:
  push:
    branches:
      - environment*
  pull_request:
    branches:
      - environment*
    paths-ignore: 
    - '**/README.md'
    - 'README.md'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install yq
        run: |
           sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64
           sudo chmod +x /usr/local/bin/yq
      - name: Run Script
        run: ./compliance-mt.sh
        env: 
          GITHUB_BASE_REF: ${{ secrets.GITHUB_BASE_REF }}
      - name: Display Output in PR
        if: always()
        run: |
          GIT_COMMENT="## ⚠ [Compliance and Multitenancy tests] Validation Failed
          <details><summary><code>detail</code></summary>
          \`\`\`
          $(echo "${OUTPUT}")
          \`\`\`
          </details>
          "

          # comment to github
          PAYLOAD=$(echo '{}' | jq --arg body "${GIT_COMMENT}" '.body = $body')
          COMMENTS_URL=$(cat ${GITHUB_EVENT_PATH} | jq -r .pull_request.comments_url)
          curl -sSv -H "Authorization: token ${GITHUB_TOKEN}" --header "Content-Type: application/json" --data "${PAYLOAD}" "${COMMENTS_URL}" >/dev/null
