name: Run Compliance and Multitenancy tests
on:
  push:
    branches:
      - environment*
  pull_request:
    branches:
      - environment*
    paths-ignore: 
    - '**/README.md'
    - 'README.md'
jobs:
  compliance-multitenancy-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install yq
        run: |
           sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64
           sudo chmod +x /usr/local/bin/yq
      - name: Run Script
        run: .github/script/compliance-mt.sh
        env: 
          GITHUB_BASE_REF: ${{ secrets.GITHUB_BASE_REF }}
